# This file is part of Karabo.
#
# http://www.karabo.eu
#
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#
# Karabo is free software: you can redistribute it and/or modify it under
# the terms of the MPL-2 Mozilla Public License.
#
# You should have received a copy of the MPL-2 Public License along with
# Karabo. If not, see <https://www.mozilla.org/en-US/MPL/2.0/>.
#
# Karabo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
[build-system]
requires = ["setuptools>=61", "setuptools-scm>=6", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# build only CPython 3.14 manylinux
build = "cp314-manylinux_*"
before-all = [
    # dependencies that can be any version
    "yum install -yq openssl-devel openssl3-devel pugixml-devel libcurl-devel zlib-devel && pip install conan numpy~=2.0.0 && conan profile detect",
    "echo $'\n[platform_requires]\nlibcurl/*\nopenssl/3\npugixml/*\nzlib/*\n' >> ~/.conan2/profiles/default",
    "cd /project/src/karabo",
    "mkdir -p build_release_cibuildwhl",
    "cd build_release_cibuildwhl",
    # dependencies that should be a specific version
    "conan install --requires=boost/1.88.0 --build=b2/* --requires=amqp-cpp/4.3.26 --requires=nlohmann_json/3.12.0 --requires=spdlog/1.14.1 -o *:shared=True --build=missing -g CMakeDeps -g CMakeToolchain --deployer=/project/extern/karabo_deployer --deployer-folder=$EXTERN_DEPS_DIR",
    "ls -la /project/src/karabo/build_release_cibuildwhl",
    "VERBOSE=1 cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$EXTERN_DEPS_DIR -DCMAKE_INSTALL_PREFIX=$EXTERN_DEPS_DIR ..",
    "VERBOSE=1 cmake --build . --target install",
]
# Pass host cache paths and configure compiler launchers inside the container
environment = { EXTERN_DEPS_DIR = "/usr", CONAN_CPU_COUNT = "1" }  #, CCACHE_DIR = "/host/tmp/ccache", CMAKE_CXX_COMPILER_LAUNCHER = "ccache", CMAKE_C_COMPILER_LAUNCHER = "ccache" }

[tool.cibuildwheel.linux]
# build only for x86 64-bit
archs = ["x86_64"]

# Note: pyproject is NOT at repo root, so point to it.
[tool.setuptools_scm]
root = "../../"
write_to = "src/pythonKarabo/karabo/_version.py"
fallback_version = "3.0.90"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"
asyncio_mode = "auto"

[tool.isort]
combine_as_imports = true
include_trailing_comma = false
multi_line_output = 4
line_length = 79
known_first_party = ["karabo", "karabind"]
src_paths = ["src"]
